pokemon_types = {
    'bulbasaur': ['grass', 'poison'],
    'ivysaur': ['grass', 'poison'],
    'venusaur': ['grass', 'poison'],
    'charmander': ['fire', 'notype'],
    'charmeleon': ['fire', 'notype'],
    'charizard': ['fire', 'flying'],
    'squirtle': ['water', 'notype'],
    'wartortle': ['water', 'notype'],
    'blastoise': ['water', 'notype'],
    'caterpie': ['bug', 'notype'],
    'metapod': ['bug', 'notype'],
    'butterfree': ['bug', 'flying'],
    'weedle': ['bug', 'poison'],
    'kakuna': ['bug', 'poison'],
    'beedrill': ['bug', 'poison'],
    'pidgey': ['normal', 'flying'],
    'pidgeotto': ['normal', 'flying'],
    'pidgeot': ['normal', 'flying'],
    'rattata': ['normal', 'notype'],
    'raticate': ['normal', 'notype'],
    'spearow': ['normal', 'flying'],
    'fearow': ['normal', 'flying'],
    'ekans': ['poison', 'notype'],
    'arbok': ['poison', 'notype'],
    'pikachu': ['electric', 'notype'],
    'raichu': ['electric', 'notype'],
    'sandshrew': ['ground', 'notype'],
    'sandslash': ['ground', 'notype'],
    'nidoranf': ['poison', 'notype'], 
    'nidorina': ['poison', 'notype'],
    'nidoqueen': ['poison', 'ground'],
    'nidoranm': ['poison', 'notype'], 
    'nidorino': ['poison', 'notype'],
    'nidoking': ['poison', 'ground'],
    'clefairy': ['normal', 'notype'], 
    'clefable': ['normal', 'notype'], 
    'vulpix': ['fire', 'notype'],
    'ninetales': ['fire', 'notype'],
    'jigglypuff': ['normal', 'notype'], 
    'wigglytuff': ['normal', 'notype'], 
    'zubat': ['poison', 'flying'],
    'golbat': ['poison', 'flying'],
    'oddish': ['grass', 'poison'],
    'gloom': ['grass', 'poison'],
    'vileplume': ['grass', 'poison'],
    'paras': ['bug', 'grass'],
    'parasect': ['bug', 'grass'],
    'venonat': ['bug', 'poison'],
    'venomoth': ['bug', 'poison'],
    'diglett': ['ground', 'notype'],
    'dugtrio': ['ground', 'notype'],
    'meowth': ['normal', 'notype'],
    'persian': ['normal', 'notype'],
    'psyduck': ['water', 'notype'],
    'golduck': ['water', 'notype'],
    'mankey': ['fighting', 'notype'],
    'primeape': ['fighting', 'notype'],
    'growlithe': ['fire', 'notype'],
    'arcanine': ['fire', 'notype'],
    'poliwag': ['water', 'notype'],
    'poliwhirl': ['water', 'notype'],
    'poliwrath': ['water', 'fighting'],
    'abra': ['psychic', 'notype'],
    'kadabra': ['psychic', 'notype'],
    'alakazam': ['psychic', 'notype'],
    'machop': ['fighting', 'notype'],
    'machoke': ['fighting', 'notype'],
    'machamp': ['fighting', 'notype'],
    'bellsprout': ['grass', 'poison'],
    'weepinbell': ['grass', 'poison'],
    'victreebel': ['grass', 'poison'],
    'tentacool': ['water', 'poison'],
    'tentacruel': ['water', 'poison'],
    'geodude': ['rock', 'ground'],
    'graveler': ['rock', 'ground'],
    'golem': ['rock', 'ground'],
    'ponyta': ['fire', 'notype'],
    'rapidash': ['fire', 'notype'],
    'slowpoke': ['water', 'psychic'],
    'slowbro': ['water', 'psychic'],
    'magnemite': ['electric', 'notype'], 
    'magneton': ['electric', 'notype'], 
    'farfetchd': ["normal", "flying"],
    'doduo': ['normal', 'flying'],
    'dodrio': ['normal', 'flying'],
    'seel': ['water', 'notype'],
    'dewgong': ['water', 'ice'],
    'grimer': ['poison', 'notype'],
    'muk': ['poison', 'notype'],
    'shellder': ['water', 'notype'],
    'cloyster': ['water', 'ice'],
    'gastly': ['ghost', 'poison'],
    'haunter': ['ghost', 'poison'],
    'gengar': ['ghost', 'poison'],
    'onix': ['rock', 'ground'],
    'drowzee': ['psychic', 'notype'],
    'hypno': ['psychic', 'notype'],
    'krabby': ['water', 'notype'],
    'kingler': ['water', 'notype'],
    'voltorb': ['electric', 'notype'],
    'electrode': ['electric', 'notype'],
    'exeggcute': ['grass', 'psychic'],
    'exeggutor': ['grass', 'psychic'],
    'cubone': ['ground', 'notype'],
    'marowak': ['ground', 'notype'],
    'hitmonlee': ['fighting', 'notype'],
    'hitmonchan': ['fighting', 'notype'],
    'lickitung': ['normal', 'notype'],
    'koffing': ['poison', 'notype'],
    'weezing': ['poison', 'notype'],
    'rhyhorn': ['ground', 'rock'],
    'rhydon': ['ground', 'rock'],
    'chansey': ['normal', 'notype'],
    'tangela': ['grass', 'notype'],
    'kangaskhan': ['normal', 'notype'],
    'horsea': ['water', 'notype'],
    'seadra': ['water', 'notype'],
    'goldeen': ['water', 'notype'],
    'seaking': ['water', 'notype'],
    'staryu': ['water', 'notype'],
    'starmie': ['water', 'psychic'],
    'mr-mime': ['psychic', 'notype'], 
    'scyther': ['bug', 'flying'],
    'jynx': ['ice', 'psychic'],
    'electabuzz': ['electric', 'notype'],
    'magmar': ['fire', 'notype'],
    'pinsir': ['bug', 'notype'],
    'tauros': ['normal', 'notype'],
    'magikarp': ['water', 'notype'],
    'gyarados': ['water', 'flying'],
    'lapras': ['water', 'ice'],
    'ditto': ['normal', 'notype'],
    'eevee': ['normal', 'notype'],
    'vaporeon': ['water', 'notype'],
    'jolteon': ['electric', 'notype'],
    'flareon': ['fire', 'notype'],
    'porygon': ['normal', 'notype'],
    'omanyte': ['rock', 'water'],
    'omastar': ['rock', 'water'],
    'kabuto': ['rock', 'water'],
    'kabutops': ['rock', 'water'],
    'aerodactyl': ['rock', 'flying'],
    'snorlax': ['normal', 'notype'],
    'articuno': ['ice', 'flying'],
    'zapdos': ['electric', 'flying'],
    'moltres': ['fire', 'flying'],
    'dratini': ['dragon', 'notype'],
    'dragonair': ['dragon', 'notype'],
    'dragonite': ['dragon', 'flying'],
    'mewtwo': ['psychic', 'notype'],
    'mew': ['psychic', 'notype']
}

status_penalties = {
    #"frz": -100, 
    "slp": -75,  
    "par": -40,  
    "tox": -25,  
    "brn": -15,  
    "psn": -15,  
     "nostatus": 0}
        

gen1_type = {
    'normal': {'rock': 0.5, 'ghost': 0.0},
    'fighting': {'normal': 2.0, 'poison': 0.5, 'flying': 0.5, 'psychic': 0.5, 'bug': 0.5, 'rock': 2.0, 'ghost': 0.0, 'ice': 2.0},
    'flying': {'fighting': 2.0, 'bug': 2.0, 'grass': 2.0, 'electric': 0.5, 'rock': 0.5},
    'poison': {'poison': 0.5, 'ground': 0.5, 'bug': 2.0, 'rock': 0.5, 'ghost': 0.5, 'grass': 2.0},
    'ground': {'fire': 2.0, 'electric': 2.0, 'poison': 2.0, 'flying': 0.0, 'bug': 0.5, 'rock': 2.0, 'grass': 0.5},
    'rock': {'fire': 2.0, 'ice': 2.0, 'fighting': 0.5, 'ground': 0.5, 'flying': 2.0, 'bug': 2.0},
    'bug': {'fire': 0.5, 'poison': 2.0, 'fighting': 0.5, 'flying': 0.5, 'psychic': 2.0, 'ghost': 0.5, 'grass': 2.0},
    'ghost': {'normal': 0.0, 'psychic': 0.0, 'ghost': 2.0}, 
    'fire': {'fire': 0.5, 'water': 0.5, 'bug': 2.0, 'rock': 0.5, 'ice': 2.0, 'grass': 2.0, 'dragon': 0.5},
    'water': {'fire': 2.0, 'water': 0.5, 'ground': 2.0, 'rock': 2.0, 'ice': 1.0, 'grass': 0.5, 'dragon': 0.5},
    'grass': {'fire': 0.5, 'water': 2.0, 'poison': 0.5, 'ground': 2.0, 'flying': 0.5, 'bug': 0.5, 'rock': 2.0, 'dragon': 0.5},
    'electric': {'water': 2.0, 'electric': 0.5, 'ground': 0.0, 'flying': 2.0, 'grass': 0.5, 'dragon': 0.5},
    'psychic': {'fighting': 2.0, 'poison': 2.0, 'psychic': 0.5, 'ghost': 0.0}, 
    'ice': {'water': 0.5, 'ground': 2.0, 'flying': 2.0, 'ice': 0.5, 'grass': 2.0, 'dragon': 2.0},
    'dragon': {'dragon': 2.0}}
